name: run test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run cd cmd
      run: cd user-dashboard-client
    - name: Run npm install
      run: npm install
    - name: run test
      run: npm test
