name: run test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run npm test
    - run: cd user-dashboard-client
    - run: npm install
    - run: npm test 
